[general]
import = [
  # themes:
  # "~/.config/alacritty/themes/catppuccin-latte.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
  # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
  # "~/.config/alacritty/themes/catppuccin-mocha.toml"
  # "~/.config/alacritty/themes/monokai-pro.toml"
  # "~/.config/alacritty/themes/solarized_dark.toml"
  # "~/.config/alacritty/themes/solarized_light.toml"
  # "~/.config/alacritty/themes/tokyo-night.toml"
  "~/.config/alacritty/themes/tokyo-night-storm.toml"
  # "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "fullscreen"
decorations = "Buttonless"
padding.x = 5
padding.y = 5
dynamic_padding = true
opacity = 0.85
# blur = true

[font]
size = 13
normal.style = "Regular"
normal.family = "VictorMono Nerd Font"
# normal.family = "SauceCodePro Nerd Font"
# normal.family = "Iosevka"
# normal.family = "ZedMono Nerd Font"
# normal.family = "MesloLGS Nerd Font Mono"

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"
