import = [
  # themes:
  # "~/.config/alacritty/themes/catppuccin-latte.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
  # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
  # "~/.config/alacritty/themes/monokai-pro.toml"
  # "~/.config/alacritty/themes/solarized_dark.toml"
  # "~/.config/alacritty/themes/solarized_light.toml"
  # "~/.config/alacritty/themes/tokyo-night.toml"
  # "~/.config/alacritty/themes/tokyo-night-storm.toml"
  # "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"


[window]
startup_mode = "fullscreen"
# padding.x = 10
# padding.y = 10
# decorations = "Buttonless"


[font]
normal.family = "SauceCodePro Nerd Font"
# normal.family = "MesloLGS Nerd Font Mono"
bold.family = "SauceCodePro Nerd Font"
italic.family = "SauceCodePro Nerd Font"

normal.style = "Regular"

size = 14


[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"

