import = [
  # themes:
  # "~/.config/alacritty/themes/catppuccin-latte.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
  # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
  # "~/.config/alacritty/themes/monokai-pro.toml"
  # "~/.config/alacritty/themes/solarized_dark.toml"
  # "~/.config/alacritty/themes/solarized_light.toml"
  # "~/.config/alacritty/themes/tokyo-night.toml"
  # "~/.config/alacritty/themes/tokyo-night-storm.toml"
]


[env]
TERM = "xterm-256color"


[font]
size = 14

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.bold]
family = "SauceCodePro Nerd Font"

[font.italic]
family = "SauceCodePro Nerd Font"


[window]
startup_mode = "fullscreen"


[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"
