#!/bin/bash

set -e

# Helper function to echo with information
info() {
  echo -e "\033[1;34m[INFO]\033[0m $*"
}

warn() {
  echo -e "\033[1;33m[WARN]\033[0m $*"
}

# Helper function for symlink creation with checks
create_symlink() {
  local target=$1
  local link=$2

  if [ -L "$link" ]; then
    info "Symlink $link already exists, leaving it in place."
  elif [ -e "$link" ]; then
    echo -e "\033[1;31m[ERROR]\033[0m $link already exists and is not a symlink."
  else
    ln -s "$target" "$link"
    info "Created symlink $link -> $target"
  fi
}

# Function to check and install package if necessary
install_package_if_needed() {
  local package=$1
  if ! command -v brew &>/dev/null; then
    info "Homebrew is not installed. Skipping installation of ${package}."
    return
  fi

  if ! brew list --formula -1 | grep -q "^${package}\$"; then
    info "Installing ${package} with brew..."
    brew install "${package}"
  else
    info "${package} is already installed."
  fi
}

# Install Ghostty terminal emulator with Starship prompt & Victor Mono font
if [[ "$OSTYPE" == "darwin"* ]]; then
  for package in ghostty starship font-victor-mono font-victor-mono-nerd-font; do
    install_package_if_needed "${package}"
  done
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  if command -v xrandr > /dev/null; then
    if ! snap list | grep -q ghostty; then
      snap install ghostty --classic
    else
      info "ghostty is already installed."
    fi
    warn "you must manually install font-victor-mono font-victor-mono-nerd-font!"
  else
    warn "Skipping ghostty installation on non-GUI system"
  fi
# else
#   "Unsupported OS type: $OSTYPE"
fi

# Install required packages for Zsh plugins and aliases
for package in direnv fzf zoxide eza gh jq; do
  install_package_if_needed "${package}"
done

# Install required packages for Yazi
for package in yazi ffmpegthumbnailer sevenzip poppler fd ripgrep imagemagick; do
  install_package_if_needed "${package}"
done
if [[ "$OSTYPE" == "darwin"* ]]; then
  install_package_if_needed "font-symbols-only-nerd-font"
fi

# Install required packages for Tmux Tokyo Night Theme
for package in bc coreutils gawk glab gsed; do
  install_package_if_needed "${package}"
done
if [[ "$OSTYPE" == "darwin"* ]]; then
  install_package_if_needed "nowplaying-cli"
fi

# Install other dependencies
for package in tmuxinator fish fisher; do
  install_package_if_needed "${package}"
done

cd ~
echo "Setting up dotfiles locally..."

if [ -d ".dotfiles" ]; then
  cd .dotfiles
  if git diff-index --quiet HEAD --; then
    info "Pulling latest changes..."
    git pull
  else
    info "There are uncommitted changes. Please commit or stash them before pulling new changes."
  fi
else
  info "Cloning dotfiles repository..."
  git clone https://github.com/jdurand/dotfiles.git .dotfiles
  # git clone git@github.com:jdurand/dotfiles.git .dotfiles
fi

# Setup Symlinks
info "Setting up home directory symlinks..."
create_symlink "$HOME/.dotfiles/zsh" "$HOME/.zsh"
create_symlink "$HOME/.dotfiles/zsh/zshrc" "$HOME/.zshrc"
create_symlink "$HOME/.dotfiles/tmux" "$HOME/.tmux"
create_symlink "$HOME/.dotfiles/tmux/tmux.conf" "$HOME/.tmux.conf"
create_symlink "$HOME/.dotfiles/vim" "$HOME/.vim"
create_symlink "$HOME/.dotfiles/vim/vimrc" "$HOME/.vimrc"
create_symlink "$HOME/.dotfiles/fzf/fzf.zsh" "$HOME/.fzf.zsh"
create_symlink "$HOME/.dotfiles/fzf" "$HOME/.fzf"
create_symlink "$HOME/.dotfiles/wezterm/config.lua" "$HOME/.wezterm.lua"

# Ensure ~/.config directory exists
info "Ensuring ~/.config directory exists..."
mkdir -p ~/.config

# Symlink directories inside ~/.dotfiles to ~/.config
cd ~/.dotfiles
for dir in alacritty kitty ghostty tmuxinator nvim bat lazygit; do
  if [ -d "$dir" ]; then
    create_symlink "$HOME/.dotfiles/$dir" "$HOME/.config/$dir"
  else
    info "Skipping $dir as it is not a directory in ~/.dotfiles"
  fi
done

# Create symlink for starship.toml
create_symlink "$HOME/.dotfiles/starship/starship.toml" "$HOME/.config/starship.toml"

# Create symlink for the default .tmuxinator.yml
create_symlink "$HOME/.dotfiles/tmuxinator/tmuxinator.yml" "$HOME/.tmuxinator.yml"

# Create symlink for config.fish & fish_plugins
create_symlink "$HOME/.dotfiles/fish/config.fish" "$HOME/.config/fish/config.fish"
create_symlink "$HOME/.dotfiles/fish/fish_plugins" "$HOME/.config/fish/fish_plugins"

# Create a symbolic links for Linux
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  create_symlink "$HOME/.dotfiles/imwheel/imwheelrc" "$HOME/.imwheelrc"
fi

# Install fish plugins
fish -c '
  for plugin in jorgebucaran/nvm.fish direnv/direnv jethrokuan/z patrickf1/fzf.fish
    fisher install $plugin
  end
'

# Check for +sketchybar option
if [[ "$1" == "+sketchybar" ]]; then
  info "Installing SketchyBar and its dependencies..."
  zsh ./_setup/install-sketchybar
  brew services restart sketchybar
fi

info "All tasks completed successfully."
