[[mgr.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd ~/Downloads"
desc = "Cd to ~/Downloads"

[[mgr.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/Pictures"
desc = "Cd to ~/Pictures"

[[mgr.append_keymap]]
on = "W"
desc = "Set as wallpaper"
run = "shell '~/.dotfiles/hypr/scripts/set-wallpaper \"$0\"'"
