# /Users/jdurand/.config/tmuxinator/config.yml

name: config
root: ~/.dotfiles
windows:
  - editor:
      layout: main-vertical
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - nvim -p ./vim/vimrc ./tmux/tmux.conf
        - nvim -p ./nvim/init.vim ./nvim/lua/plugins/todo.lua ./nvim/lua/user/settings.lua
        - nvim -p ../.config/tmuxinator/libro.yml ../.config/tmuxinator/notes.yml ../.config/tmuxinator/libro-h.yml ../.config/tmuxinator/keyboards.yml ../.config/tmuxinator/config.yml ../.config/tmuxinator/obb.yml
