# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = uwsm app -- hyprsunset-location --night-temperature 4000
exec-once = uwsm-app -- waybar-watchdog
exec-once = uwsm app -- ags run -g 4
