# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
  allow_session_lock_restore = true
}

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
  # No gaps between windows or borders
  # gaps_in = 0
  # gaps_out = 0
  # border_size = 0

  col.active_border = rgba(ffffffaa)
  col.inactive_border = rgba(ffffff33)

  # Use master layout instead of dwindle
  # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
  rounding = 16

  blur {
    brightness = 0.80
  }
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
  # Avoid overly wide single-window layouts on wide screens
  # single_window_aspect_ratio = 1 1
}

# https://wiki.hypr.land/Configuring/Scrolling-Layout/
scrolling {
  column_width = 0.8
  focus_fit_method = 0
  direction = right
}
