require("items.right.widgets.battery")
require("items.right.widgets.volume")
require("items.right.widgets.wifi")
require("items.right.widgets.cpu")
require("items.right.widgets.calendar_meetings")
require("items.right.widgets.pr_reviews")
require("items.right.widgets.jira_issues")
