# Load zap zsh plugin manager
if [ ! -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ]; then
  zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) --branch release-v1 --keep
fi
source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"

function load_theme() {
  # Load starship prompt
  eval "$(starship init zsh)"
  # or
  # Load zap prompt
  # plug "zap-zsh/zap-prompt"
}

# Load user variables
source ~/.zsh/variables.zsh

# Load theme before plugins for quicker prompt display
load_theme

# Load Extensions
source ~/.zsh/extensions.zsh

# Load all environment configuration files
if [[ -d "${HOME}/.dotfiles/environment" ]]; then
  for env_file in "${HOME}/.dotfiles/environment"/*.env; do
    [[ -f "$env_file" ]] && source "$env_file"
  done
fi

# Load local config
test -e "${HOME}/.zshrc.local" && source "${HOME}/.zshrc.local"

# Load user aliases
source ~/.zsh/aliases.zsh

# Load user aliases
source ~/.zsh/keybinds.zsh

# Cleanup unset variables to avoid conflicts
source ~/.zsh/cleanup.zsh

# Load and initialise completion system
autoload -Uz compinit
compinit
